-- AlterTable
ALTER TABLE "Pool" ADD COLUMN     "indexedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "organizerFee" DECIMAL(38,7) NOT NULL DEFAULT 0,
ADD COLUMN     "platformFee" DECIMAL(38,7) NOT NULL DEFAULT 0,
ADD COLUMN     "endedAt" TIMESTAMP(3),
ADD COLUMN     "supplierNet" DECIMAL(38,7) NOT NULL DEFAULT 0;

